<?php

namespace App\Models;

use App\SlugTrait;
use Illuminate\Database\Eloquent\Model;

class Treatment extends Model
{
    use SlugTrait;
    protected $fillable = [
        'name', 'description', 'slug', 'is_active'
    ];

    public function save(array $options = [])
    {
        return parent::save($options); // TODO: Change the autogenerated stub
    }
}
